### ISSUE TITLE
AccessToken is private

### ISSUE THREAD

**Issue by RandomErrorMessage** [mattn/go-mastodon#114]
When trying to work with AuthenticateToken I found it quite confusing on how to get the returned AccessToken. It's currently located in a private member of the client and it's unclear how the developer intends for you to save it for future use.

I ended up just temporarily modifying the code to just print it out to console, but that seems like an awful solution. I think a could solution would be return it on AuthenticateToken().

**Comment by dtluna** [comment]
I would like to save the access token too!
