### ISSUE TITLE
Add description to attachments

### ISSUE THREAD

**Issue by RasmusLindroth** [mattn/go-mastodon#129]
Hi,

UploadMedia and UploadMediaFromReader doesn't seem to support adding a description to your files or am I missing something?

I can help with a PR in that case, but want to know if it's already possible first

**Comment by mattn** [comment]
Attatchment already have description.

https://github.com/mattn/go-mastodon/blob/3e91c76504df99d2066afada755594ee8b554d1d/mastodon.go#L292

**Comment by 178inaba** [comment]
@RasmusLindroth 
Do you need the ability to add a description when uploading an image?

I implemented that feature and submitted a pull request.
https://github.com/mattn/go-mastodon/pull/130

**Comment by RasmusLindroth** [comment]
Thank you! :)
