### ISSUE TITLE
Remove 1.15 build test?

### ISSUE THREAD

**Issue by mellowdrifter** [mattn/go-mastodon#157]
This project has a go.mod version set to 1.16, but build tests are still testing on 1.15 - Is this intentional? I ask as a couple of functions were moved out of ioutil into os in 1.16 and I'd like to clean that up. But that breaks the 1.15 build

**Comment by mattn** [comment]
yeah, it should be

```
 go: ["1.16", "1.17", "1.18", "1.19"]
```
