### ISSUE TITLE
v0.0.7 `zip` and `tar.gz` files reference `rmrfslashbin/go-mastodon`

### ISSUE THREAD

**Issue by jeroen-de-bruin** [mattn/go-mastodon#192]
In both `go.mod` and `example_test.go`  the module `github.com/rmrfslashbin/go-mastodon` is used instead of `github.com/mattn/go-mastodon`. This applies to both the `zip` file and the `tar.gz` file in the `v0.0.7` release.

This reference is not used in the source code itself and it looks like it was already fixed last week but no new tag was added.

**Comment by mattn** [comment]
Will update soon

**Comment by mattn** [comment]
Released v0.0.8

**Comment by jeroen-de-bruin** [comment]
Great, thanks a lot!
