### ISSUE TITLE
client.StreamingHome: wrong url?

### ISSUE THREAD

**Issue by chneukirchen** [mattn/go-mastodon#25]
According to https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md the "home timelime" is at `/api/v1/streaming/user`, but client.StreamingHome tries `.../home`.
(Probably should be renamed to client.StreamingUser then.)

Also, it would be nice to add showing this stream this to the mstdn client. (Perhaps I'll brush up my Go and send a PR later.)

**Comment by mattn** [comment]
yes, please.

**Comment by mattn** [comment]
ping. If you still not work for this, I want to do this my-self now.

**Comment by chneukirchen** [comment]
Sorry, I've been too busy with other things. Thanks for fixing!
