### ISSUE TITLE
Provide formatted text in --json?

### ISSUE THREAD

**Issue by chneukirchen** [mattn/go-mastodon#30]
Currently, we can decide whether we want --simplejson, which lacks a lot of detail (acct, date...)
or --json, which contains all upstream data but no conveniently formatted text.

Would it be possible to add the result of textContent to the --json format too, so it's easier to work with it without formatting HTML downstream?

**Comment by mattn** [comment]
how about new flag to generate text from go's template?

```
$ mstdn stream --template "{{.Content | text}}"
```

**Comment by chneukirchen** [comment]
Great idea, I like it!
