### ISSUE TITLE
How do you add max_id, since_id, limit?

### ISSUE THREAD

**Issue by 178inaba** [mattn/go-mastodon#52]
`max_id`, `since_id`, `limit` is required with the following APIs.

* GET /api/v1/accounts/:id/followers
* GET /api/v1/accounts/:id/following
* GET /api/v1/accounts/:id/statuses
* GET /api/v1/blocks
* GET /api/v1/favourites
* GET /api/v1/follow_requests
* GET /api/v1/mutes
* GET /api/v1/notifications
* GET /api/v1/statuses/:id/reblogged_by
* GET /api/v1/statuses/:id/favourited_by
* GET /api/v1/timelines/home
* GET /api/v1/timelines/public
* GET /api/v1/timelines/tag/:hashtag

https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

I have three ideas.

1. Definitely define arguments and return values.

```go
func (c *Client) GetTimelineHome(ctx context.Context, maxID, sinceID, limit *int) (tl []*Status, retMaxID, retSinceID int, err error)
```

2. Will use the new type `Pagination`.

```go
type Pagination struct {
	MaxID   *int
	SinceID *int
	Limit   *int
}

func (c *Client) GetTimelineHome(ctx context.Context, pn *Pagination) ([]*Status, *Pagination, error)
```

3. Return the `max_id` and `since_id` using the `Timeline` type.

```go
type Timeline struct {
	Statuses []*Status
	MaxID    int
	SinceID  int
}

func (c *Client) GetTimelineHome(ctx context.Context, maxID, sinceID, limit *int) (*Timeline, error)
```

Which do you think is good?
Also, please tell me if there is any other good way.

**Comment by mattn** [comment]
Yes, This is big deal which bother me. I wonder that somesone want to get whole records for all of APIs you mentioned. I prefer `2` and not return Pagination with updating pg it self.

**Comment by 178inaba** [comment]
> I wonder that someone want to get whole records for all of APIs you mentioned.

There are possible use cases.
* Want to delete all the statuses posted.
It is necessary to know the ID of all the statuses.
* Create a GUI application using go-gtk or shiny.
When implementing the function to display the old status by scrolling,
Will get a timeline by using `max_id` when scrolling.

> I prefer `2` and not return Pagination with updating pg it self.

When geting the status at the timing of scrolling, I think that max_id should be given to the user.
The user will use the saved `max_id` at the next get timing.

**Comment by 178inaba** [comment]
This is a simple sample I think.

```go
func scroll() {
	var maxID *int64
	for {
		<-scrollCh // Scrolling will unblock the channel.
		tl, pg, err := c.GetTimelineHome(ctx, &Pagination{
			MaxID: maxID,
		})
		if err != nil {
			log.Fatal(err)
		}

		maxID = pg.MaxID
	}
}
```

**Comment by mattn** [comment]
> Want to delete all the statuses posted.

Ah, make sense. Okay, let's update the signature to add Pagination for the funcs which return list.

**Comment by 178inaba** [comment]
OK!
I think that we can start this issue within this week.

**Comment by 178inaba** [comment]
Complete!
#54

**Comment by 178inaba** [comment]
The issue was settled.
Thank you very much.
