### ISSUE TITLE
Add warning that 2 factor is unsupported

### ISSUE THREAD

**Issue by shanemhansen** [mattn/go-mastodon#78]
I'm not sure if this is a library limitation or not, but I noticed that I received invalid_grant errors until I turned off 2factor.

**Comment by masterodie** [comment]
This is an API limitation. When using 2FA you are required to use OAuth.

https://github.com/tootsuite/documentation/blob/master/Using-the-API/Tips-for-app-developers.md

https://github.com/tootsuite/documentation/blob/master/Using-the-API/OAuth-details.md

**Comment by muesli** [comment]
This might be fixed in master now.
