### ISSUE TITLE
Pagination not working with GetTimelinePublic and Mastodon 2.6.5

### ISSUE THREAD

**Issue by marians** [mattn/go-mastodon#86]
I tried using go-mastodon against the `https://chaos.social` instance, which uses version 2.6.5 according to https://chaos.social/api/v1/instance, with following code:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/mattn/go-mastodon"
)

func main() {
	ctx := context.Background()

	c := mastodon.NewClient(&mastodon.Config{
		Server: "https://chaos.social",
	})

	pg := mastodon.Pagination{}

	for {
		timeline, err := c.GetTimelinePublic(ctx, false, &pg)
		if err != nil {
			log.Println(err)
		}

		for _, item := range timeline {
			fmt.Printf("%#v\n", item)
		}

		if pg.MaxID == "" {
			break
		}

		time.Sleep(10 * time.Second)
	}
}
```

This quits with the output

```
2018/12/21 07:25:04 strconv.ParseInt: parsing "": invalid syntax
```

which is coming from https://github.com/mattn/go-mastodon/blob/4def10a243942ff1ce05750f4d1846f3917bd502/mastodon.go#L296

I have an experimental fix that works for me here for the simple purpose of the above code: https://github.com/marians/go-mastodon/pull/1/files

My understanding of the Mastodon API version differences is not deep enough to tell when `min_id` has been introduced, where it is used, whether `since_id` is still in use etc. So I can't provide a PR currently that makes pagination work in all cases. Hopefully the description is enough for others to do so. Thanks!

**Comment by mattn** [comment]
@178inaba Can you handle this issue?

**Comment by 178inaba** [comment]
@mattn OK!

**Comment by marians** [comment]
@178inaba I'd rather not do that. Because (a) the change is trivial and (b) according to my understanding, especially from your comment, this will break pagination for servers < 2.6.0.

**Comment by 178inaba** [comment]
@marians Thank you.
I will consider how to fix it.

**Comment by 178inaba** [comment]
@marians I am sorry to be late.
I fixed it with #90 !
Please check it!

**Comment by marians** [comment]
Thanks! Not sure when I'll be able to test this. Will close for now.

**Comment by mattn** [comment]
@178inaba Thank you so much!
