### ISSUE TITLE
pagination since_id is ignored when max_id is set

### ISSUE THREAD

**Issue by pacmessica** [mattn/go-mastodon#89]
For example, if I have the following statusIDs.
100, 99, 98 ... 1

If I make the following call:
/api/v1/timelines/public?since_id=74&max_id=78

I would expect the following results:  [77, 76, 75]. This is also what I get when I call the api directly.

However, what I currently see is : [77, 76, 75, 74, 73, 72, ... etc]

I don't understand why go-mastodon deliberately sets since_id to an empty string if a max_id is specified. I would like to be able to paginate through the results until I reach the since_id that I specified, but that's not currently possible because when I specify a max_id, then my since_id value is ignored...

Instead of https://github.com/mattn/go-mastodon/blob/master/mastodon.go#L311
```
func (p *Pagination) setValues(params url.Values) url.Values {
	if p.MaxID != "" {
		params.Set("max_id", string(p.MaxID))
	} else if p.SinceID != "" {
		params.Set("since_id", string(p.SinceID))
	}
	if p.Limit > 0 {
		params.Set("limit", fmt.Sprint(p.Limit))
	}

	return params
}
```

why not?:
```
	if p.MaxID != "" {
		params.Set("max_id", string(p.MaxID))
	}
if p.SinceID != "" {
		params.Set("since_id", string(p.SinceID))
	}
```

**Comment by 178inaba** [comment]
This issue is discussed at #86

**Comment by 178inaba** [comment]
@pacmessica I am sorry to be late.
I fixed it with #90 !
Please check it!

**Comment by pacmessica** [comment]
great, thanks!

**Comment by mattn** [comment]
closable?
